"""initial e2ee schema

Revision ID: 7ab4e21f3b36
Revises: 
Create Date: 2026-09-03 12:23:10.636803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7ab4e21f3b36'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('device_attestations', 'signature',
               existing_type=mysql.TINYBLOB(),
               type_=sa.LargeBinary(length=64),
               existing_nullable=False)
    op.alter_column('device_log', 'prev_hash',
               existing_type=mysql.TINYBLOB(),
               type_=sa.LargeBinary(length=32),
               existing_nullable=False)
    op.alter_column('device_log', 'entry_hash',
               existing_type=mysql.TINYBLOB(),
               type_=sa.LargeBinary(length=32),
               existing_nullable=False)
    op.alter_column('devices', 'identity_pubkey',
               existing_type=mysql.TINYBLOB(),
               type_=sa.LargeBinary(length=32),
               existing_nullable=False)
    op.alter_column('one_time_prekeys', 'pubkey',
               existing_type=mysql.TINYBLOB(),
               type_=sa.LargeBinary(length=33),
               existing_nullable=False)
    op.alter_column('signed_prekeys', 'pubkey',
               existing_type=mysql.TINYBLOB(),
               type_=sa.LargeBinary(length=33),
               existing_nullable=False)
    op.alter_column('signed_prekeys', 'signature',
               existing_type=mysql.TINYBLOB(),
               type_=sa.LargeBinary(length=64),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('signed_prekeys', 'signature',
               existing_type=sa.LargeBinary(length=64),
               type_=mysql.TINYBLOB(),
               existing_nullable=False)
    op.alter_column('signed_prekeys', 'pubkey',
               existing_type=sa.LargeBinary(length=33),
               type_=mysql.TINYBLOB(),
               existing_nullable=False)
    op.alter_column('one_time_prekeys', 'pubkey',
               existing_type=sa.LargeBinary(length=33),
               type_=mysql.TINYBLOB(),
               existing_nullable=False)
    op.alter_column('devices', 'identity_pubkey',
               existing_type=sa.LargeBinary(length=32),
               type_=mysql.TINYBLOB(),
               existing_nullable=False)
    op.alter_column('device_log', 'entry_hash',
               existing_type=sa.LargeBinary(length=32),
               type_=mysql.TINYBLOB(),
               existing_nullable=False)
    op.alter_column('device_log', 'prev_hash',
               existing_type=sa.LargeBinary(length=32),
               type_=mysql.TINYBLOB(),
               existing_nullable=False)
    op.alter_column('device_attestations', 'signature',
               existing_type=sa.LargeBinary(length=64),
               type_=mysql.TINYBLOB(),
               existing_nullable=False)
    # ### end Alembic commands ###
